/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        useESM: true,
        tsconfig: 'tsconfig.jest.json',
        isolatedModules: true,
        diagnostics: false,
      },
    ],
  },
  roots: ['<rootDir>/packages', '<rootDir>/apps'],
  testMatch: [
    '**/__tests__/**/*.test.ts',
    '**/__tests__/**/*.spec.ts',
    '**/__tests__/**/*.test.tsx',
    '**/__tests__/**/*.spec.tsx',
  ],
  setupFilesAfterEnv: ['<rootDir>/apps/frontend/src/setupTests.ts'],
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '\\.(jpg|jpeg|png|gif|svg|ico|webp|avif)$': '<rootDir>/__mocks__/fileMock.js',
    '^@shared/([^/]+)(.*)$': '<rootDir>/packages/shared-$1/src$2',
    '^@types(?:/(.*))?$': '<rootDir>/packages/shared-types/src/$1',
    '^@events(?:/(.*))?$': '<rootDir>/packages/shared-events/src/$1',
    '^@auth(?:/(.*))?$': '<rootDir>/packages/shared-auth/src/$1',
    '^@rabbitmq(?:/(.*))?$': '<rootDir>/packages/shared-rabbitmq/src/$1',
    '^@logger(?:/(.*))?$': '<rootDir>/packages/shared-logger/src/$1',
    '^@inventory/shared-types$': '<rootDir>/packages/shared-types/src',
    '^@inventory/shared-types/(.*)$': '<rootDir>/packages/shared-types/src/$1',
    '^@inventory/shared-events$': '<rootDir>/packages/shared-events/src',
    '^@inventory/shared-events/(.*)$': '<rootDir>/packages/shared-events/src/$1',
    '^@inventory/shared-auth$': '<rootDir>/packages/shared-auth/src',
    '^@inventory/shared-auth/(.*)$': '<rootDir>/packages/shared-auth/src/$1',
    '^@inventory/shared-rabbitmq$': '<rootDir>/packages/shared-rabbitmq/src',
    '^@inventory/shared-rabbitmq/(.*)$': '<rootDir>/packages/shared-rabbitmq/src/$1',
    '^@inventory/shared-logger$': '<rootDir>/packages/shared-logger/src',
    '^@inventory/shared-logger/(.*)$': '<rootDir>/packages/shared-logger/src/$1',
    '^@/(.*)$': '<rootDir>/apps/frontend/src/$1',
    '^@config/([^/]+)(.*)$': '<rootDir>/packages/$1/src/config$2',
    '^@utils/([^/]+)(.*)$': '<rootDir>/packages/$1/src/utils$2',
  },
  collectCoverageFrom: [
    'packages/**/src/**/*.{ts,tsx}',
    'apps/**/src/**/*.{ts,tsx}',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/__tests__/**',
    '!**/index.ts',
    '!**/app.ts',
    '!**/config.ts',
    '!**/routes/**',
    '!**/swagger/**',
    '!**/interfaces/**',
    '!apps/frontend/src/main.tsx',
    '!apps/frontend/src/vite-env.d.ts',
    '!**/*.d.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageProvider: 'v8',
  coverageThreshold: {
    global: {
      statements: 80,
      functions: 80,
      branches: 80,
      lines: 80,
    },
  },
  clearMocks: true,
  restoreMocks: true,
  resetMocks: true,
  detectOpenHandles: false,
  maxWorkers: 4,
  testTimeout: 10000,
  errorOnDeprecated: true,
};
