import { VERSION } from './versions';

export const EVENT_VERSION = 'v1' as const;

export const EventType = {
  PRODUCT_CREATED: VERSION.PRODUCT_CREATED.type,
  PRODUCT_UPDATED: VERSION.PRODUCT_UPDATED.type,
  PRODUCT_DELETED: VERSION.PRODUCT_DELETED.type,
  STOCK_IN_CREATED: VERSION.STOCK_IN_CREATED.type,
  STOCK_OUT_CREATED: VERSION.STOCK_OUT_CREATED.type,
  STOCK_ADJUSTMENT_CREATED: VERSION.STOCK_ADJUSTMENT_CREATED.type,
  LOW_STOCK_DETECTED: VERSION.LOW_STOCK_DETECTED.type,
  USER_CREATED: VERSION.USER_CREATED.type,
  USER_UPDATED: VERSION.USER_UPDATED.type,
  AUDIT_LOGGED: VERSION.AUDIT_LOGGED.type,
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];
